// Generated by gencpp from file NESLMessages/PersonArr.msg
// DO NOT EDIT!


#ifndef NESLMESSAGES_MESSAGE_PERSONARR_H
#define NESLMESSAGES_MESSAGE_PERSONARR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <NESLMessages/Person.h>

namespace NESLMessages
{
template <class ContainerAllocator>
struct PersonArr_
{
  typedef PersonArr_<ContainerAllocator> Type;

  PersonArr_()
    : header()
    , personArr()  {
    }
  PersonArr_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , personArr(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::NESLMessages::Person_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::NESLMessages::Person_<ContainerAllocator> >> _personArr_type;
  _personArr_type personArr;





  typedef boost::shared_ptr< ::NESLMessages::PersonArr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::NESLMessages::PersonArr_<ContainerAllocator> const> ConstPtr;

}; // struct PersonArr_

typedef ::NESLMessages::PersonArr_<std::allocator<void> > PersonArr;

typedef boost::shared_ptr< ::NESLMessages::PersonArr > PersonArrPtr;
typedef boost::shared_ptr< ::NESLMessages::PersonArr const> PersonArrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::NESLMessages::PersonArr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::NESLMessages::PersonArr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::NESLMessages::PersonArr_<ContainerAllocator1> & lhs, const ::NESLMessages::PersonArr_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.personArr == rhs.personArr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::NESLMessages::PersonArr_<ContainerAllocator1> & lhs, const ::NESLMessages::PersonArr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace NESLMessages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::NESLMessages::PersonArr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::NESLMessages::PersonArr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NESLMessages::PersonArr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NESLMessages::PersonArr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NESLMessages::PersonArr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NESLMessages::PersonArr_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::NESLMessages::PersonArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fc894af3e67e11ac542d4784fd5fbb1";
  }

  static const char* value(const ::NESLMessages::PersonArr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fc894af3e67e11aULL;
  static const uint64_t static_value2 = 0xc542d4784fd5fbb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::NESLMessages::PersonArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NESLMessages/PersonArr";
  }

  static const char* value(const ::NESLMessages::PersonArr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::NESLMessages::PersonArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Person[] personArr\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: NESLMessages/Person\n"
"float64[] colorArr\n"
"int32 personID\n"
"NeslCoord personCoord\n"
"bool accountedFor\n"
"bool talking\n"
"float32 bbx\n"
"float32 bby\n"
"float32 bbz\n"
"\n"
"================================================================================\n"
"MSG: NESLMessages/NeslCoord\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::NESLMessages::PersonArr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::NESLMessages::PersonArr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.personArr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonArr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::NESLMessages::PersonArr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::NESLMessages::PersonArr_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "personArr[]" << std::endl;
    for (size_t i = 0; i < v.personArr.size(); ++i)
    {
      s << indent << "  personArr[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::NESLMessages::Person_<ContainerAllocator> >::stream(s, indent + "    ", v.personArr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NESLMESSAGES_MESSAGE_PERSONARR_H
