// Generated by gencpp from file fdopencv_msgs/ImageMapVal.msg
// DO NOT EDIT!


#ifndef FDOPENCV_MSGS_MESSAGE_IMAGEMAPVAL_H
#define FDOPENCV_MSGS_MESSAGE_IMAGEMAPVAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace fdopencv_msgs
{
template <class ContainerAllocator>
struct ImageMapVal_
{
  typedef ImageMapVal_<ContainerAllocator> Type;

  ImageMapVal_()
    : id(0)
    , img()  {
    }
  ImageMapVal_(const ContainerAllocator& _alloc)
    : id(0)
    , img(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> const> ConstPtr;

}; // struct ImageMapVal_

typedef ::fdopencv_msgs::ImageMapVal_<std::allocator<void> > ImageMapVal;

typedef boost::shared_ptr< ::fdopencv_msgs::ImageMapVal > ImageMapValPtr;
typedef boost::shared_ptr< ::fdopencv_msgs::ImageMapVal const> ImageMapValConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator1> & lhs, const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.img == rhs.img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator1> & lhs, const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fdopencv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec273785f6797c77d37579f49be2dd3b";
  }

  static const char* value(const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec273785f6797c77ULL;
  static const uint64_t static_value2 = 0xd37579f49be2dd3bULL;
};

template<class ContainerAllocator>
struct DataType< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdopencv_msgs/ImageMapVal";
  }

  static const char* value(const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"sensor_msgs/Image img\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageMapVal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fdopencv_msgs::ImageMapVal_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FDOPENCV_MSGS_MESSAGE_IMAGEMAPVAL_H
