// Generated by gencpp from file hark_msgs/HarkWave.msg
// DO NOT EDIT!


#ifndef HARK_MSGS_MESSAGE_HARKWAVE_H
#define HARK_MSGS_MESSAGE_HARKWAVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hark_msgs/HarkWaveVal.h>

namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkWave_
{
  typedef HarkWave_<ContainerAllocator> Type;

  HarkWave_()
    : header()
    , count(0)
    , nch(0)
    , length(0)
    , data_bytes(0)
    , src()  {
    }
  HarkWave_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , nch(0)
    , length(0)
    , data_bytes(0)
    , src(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _count_type;
  _count_type count;

   typedef int32_t _nch_type;
  _nch_type nch;

   typedef int32_t _length_type;
  _length_type length;

   typedef int32_t _data_bytes_type;
  _data_bytes_type data_bytes;

   typedef std::vector< ::hark_msgs::HarkWaveVal_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hark_msgs::HarkWaveVal_<ContainerAllocator> >> _src_type;
  _src_type src;





  typedef boost::shared_ptr< ::hark_msgs::HarkWave_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkWave_<ContainerAllocator> const> ConstPtr;

}; // struct HarkWave_

typedef ::hark_msgs::HarkWave_<std::allocator<void> > HarkWave;

typedef boost::shared_ptr< ::hark_msgs::HarkWave > HarkWavePtr;
typedef boost::shared_ptr< ::hark_msgs::HarkWave const> HarkWaveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hark_msgs::HarkWave_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hark_msgs::HarkWave_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hark_msgs::HarkWave_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkWave_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.count == rhs.count &&
    lhs.nch == rhs.nch &&
    lhs.length == rhs.length &&
    lhs.data_bytes == rhs.data_bytes &&
    lhs.src == rhs.src;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hark_msgs::HarkWave_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkWave_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hark_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkWave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkWave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkWave_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkWave_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkWave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkWave_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkWave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24c5654436a3ff03c563377fdbcc56a1";
  }

  static const char* value(const ::hark_msgs::HarkWave_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24c5654436a3ff03ULL;
  static const uint64_t static_value2 = 0xc563377fdbcc56a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkWave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hark_msgs/HarkWave";
  }

  static const char* value(const ::hark_msgs::HarkWave_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkWave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 count\n"
"int32 nch\n"
"int32 length\n"
"int32 data_bytes\n"
"HarkWaveVal[] src # Audio stream and source info for each source\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hark_msgs/HarkWaveVal\n"
"float32[] wavedata\n"
;
  }

  static const char* value(const ::hark_msgs::HarkWave_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkWave_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.nch);
      stream.next(m.length);
      stream.next(m.data_bytes);
      stream.next(m.src);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarkWave_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkWave_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hark_msgs::HarkWave_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "nch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nch);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
    s << indent << "data_bytes: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data_bytes);
    s << indent << "src[]" << std::endl;
    for (size_t i = 0; i < v.src.size(); ++i)
    {
      s << indent << "  src[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hark_msgs::HarkWaveVal_<ContainerAllocator> >::stream(s, indent + "    ", v.src[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKWAVE_H
