// Generated by gencpp from file hark_msgs/HarkInt.msg
// DO NOT EDIT!


#ifndef HARK_MSGS_MESSAGE_HARKINT_H
#define HARK_MSGS_MESSAGE_HARKINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkInt_
{
  typedef HarkInt_<ContainerAllocator> Type;

  HarkInt_()
    : data(0)  {
    }
  HarkInt_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int64_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hark_msgs::HarkInt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkInt_<ContainerAllocator> const> ConstPtr;

}; // struct HarkInt_

typedef ::hark_msgs::HarkInt_<std::allocator<void> > HarkInt;

typedef boost::shared_ptr< ::hark_msgs::HarkInt > HarkIntPtr;
typedef boost::shared_ptr< ::hark_msgs::HarkInt const> HarkIntConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hark_msgs::HarkInt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hark_msgs::HarkInt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hark_msgs::HarkInt_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkInt_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hark_msgs::HarkInt_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkInt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hark_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkInt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkInt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34add168574510e6e17f5d23ecc077ef";
  }

  static const char* value(const ::hark_msgs::HarkInt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34add168574510e6ULL;
  static const uint64_t static_value2 = 0xe17f5d23ecc077efULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hark_msgs/HarkInt";
  }

  static const char* value(const ::hark_msgs::HarkInt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 data\n"
;
  }

  static const char* value(const ::hark_msgs::HarkInt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkInt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarkInt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hark_msgs::HarkInt_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKINT_H
