// Generated by gencpp from file hark_msgs/HarkIntSrv.msg
// DO NOT EDIT!


#ifndef HARK_MSGS_MESSAGE_HARKINTSRV_H
#define HARK_MSGS_MESSAGE_HARKINTSRV_H

#include <ros/service_traits.h>


#include <hark_msgs/HarkIntSrvRequest.h>
#include <hark_msgs/HarkIntSrvResponse.h>


namespace hark_msgs
{

struct HarkIntSrv
{

typedef HarkIntSrvRequest Request;
typedef HarkIntSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HarkIntSrv
} // namespace hark_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hark_msgs::HarkIntSrv > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::hark_msgs::HarkIntSrv&) { return value(); }
};

template<>
struct DataType< ::hark_msgs::HarkIntSrv > {
  static const char* value()
  {
    return "hark_msgs/HarkIntSrv";
  }

  static const char* value(const ::hark_msgs::HarkIntSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hark_msgs::HarkIntSrvRequest> should match
// service_traits::MD5Sum< ::hark_msgs::HarkIntSrv >
template<>
struct MD5Sum< ::hark_msgs::HarkIntSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hark_msgs::HarkIntSrv >::value();
  }
  static const char* value(const ::hark_msgs::HarkIntSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hark_msgs::HarkIntSrvRequest> should match
// service_traits::DataType< ::hark_msgs::HarkIntSrv >
template<>
struct DataType< ::hark_msgs::HarkIntSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hark_msgs::HarkIntSrv >::value();
  }
  static const char* value(const ::hark_msgs::HarkIntSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hark_msgs::HarkIntSrvResponse> should match
// service_traits::MD5Sum< ::hark_msgs::HarkIntSrv >
template<>
struct MD5Sum< ::hark_msgs::HarkIntSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hark_msgs::HarkIntSrv >::value();
  }
  static const char* value(const ::hark_msgs::HarkIntSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hark_msgs::HarkIntSrvResponse> should match
// service_traits::DataType< ::hark_msgs::HarkIntSrv >
template<>
struct DataType< ::hark_msgs::HarkIntSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hark_msgs::HarkIntSrv >::value();
  }
  static const char* value(const ::hark_msgs::HarkIntSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKINTSRV_H
