// Generated by gencpp from file hark_msgs/HarkIntSrvResponse.msg
// DO NOT EDIT!


#ifndef HARK_MSGS_MESSAGE_HARKINTSRVRESPONSE_H
#define HARK_MSGS_MESSAGE_HARKINTSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkIntSrvResponse_
{
  typedef HarkIntSrvResponse_<ContainerAllocator> Type;

  HarkIntSrvResponse_()
    : result(0)  {
    }
  HarkIntSrvResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HarkIntSrvResponse_

typedef ::hark_msgs::HarkIntSrvResponse_<std::allocator<void> > HarkIntSrvResponse;

typedef boost::shared_ptr< ::hark_msgs::HarkIntSrvResponse > HarkIntSrvResponsePtr;
typedef boost::shared_ptr< ::hark_msgs::HarkIntSrvResponse const> HarkIntSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator1> & lhs, const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hark_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hark_msgs/HarkIntSrvResponse";
  }

  static const char* value(const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
"\n"
;
  }

  static const char* value(const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarkIntSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hark_msgs::HarkIntSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKINTSRVRESPONSE_H
